# This workflow will install dependencies, build st-pydantic, run tests (+coverage) and lint

name: build

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  run_image:
    runs-on: [ubuntu-latest]
    container:
      image: matanrubin/python-poetry:3.10-1.6.1
    steps:
      - uses: actions/checkout@v4
      - run: make bootstrap
      - run: poetry build -vvv
      - run: make coverage
      - run: make check
      - run: make coverage

      # Upload coverage files to codecov
#      - uses: actions/upload-artifact@v2
#        with:
#          name: htmlcov.zip
#          path: htmlcov/
#      - uses: codecov/codecov-action@v1
