# This workflow will build st-pydantic, and publish it to pypi.org

name: publish

on:
  release:
    types: [published]

jobs:
  run_image:
    runs-on: [ubuntu-latest]
    container:
      image: matanrubin/python-poetry:3.10-1.6.1

    steps:
      - uses: actions/checkout@v2
      - run: make bootstrap
      - run: poetry update -vvv
      - run: poetry build -vvv
      - run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
